cert-manager delegation stage 2
IBM/ibm-cert-manager-operator pull request #268
Opened 2022-07-14 20:09 UTC by qpdpQ

2022-07-14 20:31 UTC, qpdpQ commented
/test check ibm-cert-manager-operator

2022-07-15 17:48 UTC, bitscuit requested changes

2022-07-15 17:48 UTC, bitscuit commented on controllers/cert-manager/podrefresh_controller.go
> +	if err := r.waitResourceReady("apiextensions.k8s.io/v1", "CustomResourceDefinition"); err != nil {
```suggestion
	if err := r.waitResourceReady("cert-manager.io/v1", "Certificate"); err != nil {
```

Shouldn't we be waiting for the cert-manager CRD specifically?

2022-07-15 17:48 UTC, bitscuit commented on controllers/certmanager/certificate_controller.go
> +	if err := r.waitResourceReady("apiextensions.k8s.io/v1", "CustomResourceDefinition"); err != nil {
Again, shouldn't we be watching for cert-manager CRD (either Issuer or Certificate depending on the controller) specifically?

2022-07-15 17:48 UTC, bitscuit commented on controllers/operator/v1CRDs.go
> +    app.kubernetes.io/version: "v1.9.0-alpha.0"
We should use the v1.7.1 CRDs because that is what we deploy

2022-07-15 18:48 UTC, Daniel-Fan approved these changes
/lgtm

2022-07-15 18:49 UTC, merged