cert-manager-operator automatically detect cert-manager on cluster
IBM/ibm-cert-manager-operator pull request #272
Opened 2022-08-08 22:30 UTC by qpdpQ

2022-08-18 23:21 UTC, bitscuit requested changes

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +			return ctrl.Result{RequeueAfter: time.Second * 30}, nil
Cannot simply re-queue if we hit this error because in fresh installation on a cluster that previously had CS, then there will be infinite loop since the webhookconfiguration will already exist, but no cert-manager-webhook running.

Instead, need to check for a `ValidatingWebhookConfiguration` with the following name https://github.com/IBM/ibm-cert-manager-operator/blob/master/controllers/resources/webhook_resources.go#L135. This is our webhook configuration, and then also check to see if it has this label `"app":                          "ibm-cert-manager-webhook"`. If these conditions are true, then that means our operand was deployed before, and we should continue to deploy our operand

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +		}
Add an else, so that if it is not the call webhook error, then requeue because that means something went wrong with k8s trying to create the Issuer

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +	// check certificate has status
incorrect comment

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +	// delete certificate and issuer
incorrect comment

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +	// deploy only issuer
unnecessary comment

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +// get the status of example certificate
incorrect comment

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +	//
remove `//`

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +		logd.Error(err, "Can't get examplecertificate")
incorrect message

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/exampleCert.go
> +//
this file is unnecessary. We do not need to create/delete from YAML. We already have the Issuer object available in the v1apis folder, so just import them, and then create the object. See here for example https://github.com/IBM/ibm-cert-manager-operator/blob/master/controllers/certmanager/issuer_controller.go#L113

2022-08-18 23:21 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +		return fmt.Errorf("this controller don't have correct label")
This is not error type. How can this be returned?

2022-08-23 21:23 UTC, bitscuit requested changes

2022-08-23 21:23 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +func (r *CertManagerReconciler) CreateFromYaml(yamlContent []byte, alwaysUpdate ...bool) error {
Can delete this function now that it's not being used, right?

2022-08-23 21:23 UTC, bitscuit commented on controllers/operator/certmanager_controller.go
> +func (r *CertManagerReconciler) DeleteFromYaml(yamlContent []byte, alwaysUpdate ...bool) error {
Can delete this too, right?

2022-08-24 02:14 UTC, qpdpQ commented on controllers/operator/certmanager_controller.go
> +func (r *CertManagerReconciler) CreateFromYaml(yamlContent []byte, alwaysUpdate ...bool) error {
yeah that's true, we don't need this anymore

2022-08-29 22:13 UTC, bitscuit commented on controllers/operator/util.go
> +func Namespacelize(resource, placeholder, ns string) string {
this can be removed now too, right?

2022-08-30 20:53 UTC, qpdpQ commented on controllers/operator/util.go
> +func Namespacelize(resource, placeholder, ns string) string {
yeah agree

2022-11-04 19:15 UTC, closed without merging